version: '3.9'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
